# Generated by Django 3.2.4 on 2021-07-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
