# Generated by Django 3.2.4 on 2021-07-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='fecha',
            new_name='fecha_nacimiento',
        ),
    ]
